#!/bin/bash

for file in `ls *js | grep -v '3d-cube' | grep -v 'date-format-tofte' | grep -v 'date-format-xparb'`
do
  /home/dimvar/moz/jsctags-wcopy/bin/jsctags.js "$file"
  mv tags `basename "$file" .js`.tags
done

